spring:
  datasource:
    url: jdbc:h2:mem://localhost~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

jwt:
  secret: YXZhdGFydHJpcGF1dGhvcml6YXRpb25qd3RtYW5hZ2VzZWNyZXRrZXkK
  header: Authorization
  expired-in: 600000 # 10 min
  refresh-expired-in: 86400000 # 24 hour